version: '3'

services:
        portainer:
                image: portainer/portainer
                ports:
                        - "9000:9000"
                command: -H unix:///var/run/docker.sock
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - portainer_data:/data
                labels:
                        - "traefik.frontend.rule=Host:port.srv.tmpry.com"
        traefik:
                image: traefik # The official Traefik docker image
                command: --api --docker # Enables the web UI and tells Traefik to listen to docker
                ports:
                        - "80:80"     # The HTTP port
                        - "8080:8080" # The Web UI (enabled by --api)
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
                labels:
                        - "traefik.frontend.rule=Host:traefik.srv.tmpry.com"
        whoami:
                image: emilevauge/whoami # A container that exposes an API to show its IP address
                labels:
                        - "traefik.frontend.rule=Host:whoami.srv.tmpry.com"
        echo:
                image: paddycarey/go-echo
                labels:
                        - "traefik.frontend.rule=Host:echo.srv.tmpry.com"
        transfersh:
                image: dutchcoders/transfer.sh:latest
                command: --provider local --basedir /tmp/
                ports:
                        - "8081:8080"
                labels:
                        - "traefik.frontend.rule=Host:transfer.srv.tmpry.com"
volumes:
        portainer_data:
